verbose = true
skip_children = false
max_width = 999
ideal_width = 80
tab_spaces = 2
fn_call_width = 60
struct_lit_width = 16
newline_style = "Unix"
fn_brace_style = "SameLineWhere"
item_brace_style = "SameLineWhere"
impl_empty_single_line = true
fn_empty_single_line = true
fn_single_line = false
fn_return_indent = "WithArgs"
fn_args_paren_newline = true
fn_args_density = "Tall"
fn_args_layout = "Visual"
fn_arg_indent = "Visual"
type_punctuation_density = "Wide"
where_density = "CompressedIfEmpty"
where_indent = "Tabbed"
where_layout = "Vertical"
where_pred_indent = "Visual"
generics_indent = "Visual"
struct_trailing_comma = "Never"
struct_lit_trailing_comma = "Never"
struct_lit_style = "Block"
struct_lit_multiline_style = "PreferSingle"
enum_trailing_comma = false
report_todo = "Always"
report_fixme = "Always"
chain_base_indent = "Inherit"
chain_indent = "Inherit"
reorder_imports = false
single_line_if_else = false
format_strings = true
chains_overflow_last = true
take_source_hints = true
hard_tabs = false
wrap_comments = false
normalise_comments = true
wrap_match_arms = true
match_block_trailing_comma = false
match_wildcard_trailing_comma = false
write_mode = "Overwrite"
